Ported to 1.17.1 and added Finnish translation
cominixo/BetterF3 pull request #47
Opened 2021-10-17 12:53 UTC by vil

2021-10-17 12:59 UTC, cominixo commented
Thanks for the contribution! Wasn't really necessary to update the dev environment to 1.17.1 because it was already working in 1.17.1, but good to keep it updated anyway.
I'll approve this for now and merge when I have more time to test this

2021-10-17 13:00 UTC, cominixo approved these changes

2021-10-17 13:04 UTC, HerraVp commented
Alright :D

2021-10-17 22:14 UTC, TreyRuffy requested changes
We should keep the version on 0.11.3/7 while we wait for Fabric Loader 0.12 to become stable.

Other than that I think it is good and I will upload the translation to the Crowdin page.

2021-10-17 22:14 UTC, TreyRuffy commented on src/main/resources/fabric.mod.json
> +    "fabricloader": ">=0.12.2",
We want to leave the required fabric loader on 0.11.3 (possibly changed to 0.11.7) because 0.12 is marked unstable at the moment, as seen [here](https://meta.fabricmc.net/v2/versions/loader).

2021-10-18 11:07 UTC, vil commented on src/main/resources/fabric.mod.json
> +    "fabricloader": ">=0.12.2",
Yeah alright. Im going to change that.

2021-10-18 15:08 UTC, TreyRuffy approved these changes

2021-10-26 02:56 UTC, merged